# Generated by Django 2.0.13 on 2019-06-29 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190628_1659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='published_data',
            new_name='published_date',
        ),
    ]
